export const ArticleType = [
    { label: 'Blog Post', value: 'Blog Post' },
    { label: 'Amazon Product Roundup', value: 'Amazon Product Roundup' },
    { label: 'Youtube Video to Blog Post', value: 'Youtube Video to Blog Post' },
];
export const ToneVoice = [
    { label: 'SEO Optimized (Confident, Knowledgeable, Neutral, and Clear)', value: 'seo_optimized' },
    { label: 'Excited', value: 'excited' },
    { label: 'Professional', value: 'professional' },
    { label: 'Friendly', value: 'friendly' },
    { label: 'Formal', value: 'formal' },
    { label: 'Casual', value: 'casual' },
    { label: 'Humorous', value: 'humorous' },

]
export const Language = [
    { label: 'Afrikaans', value: 'Afrikaans' },
    { label: 'Albanian',  value: 'Albanian' },
    { label: 'Amharic', value: 'Amharic' },
    { label: 'Arabic', value: 'Arabic' },
    { label: 'Armenian', value: 'Armenian' },
    { label: 'Azerbaijani', value: 'Azerbaijani' },
    { label: 'Basque', value: 'Basque' },
    { label: 'Belarusian', value: 'Belarusian' },
    { label: 'Bengali', value: 'Bengali' },
    { label: 'Bosnian', value: 'Bosnian' },
    { label: 'Bulgarian', value: 'Bulgarian' },
    { label: 'Catalan', value: 'Catalan' },
    { label: 'Cebuano', value: 'Cebuano' },
    { label: 'Chinese (Simplified)', value: 'Chinese (Simplified)' },
    { label: 'Chinese (Traditional)', value: 'Chinese (Traditional)' },
    { label: 'Corsican', value: 'Corsican' },
    { label: 'Croatian', value: 'Croatian' },
    { label: 'Czech', value: 'Czech' },
    { label: 'Danish', value: 'Danish' },
    { label: 'Dutch', value: 'Dutch' },
    { label: 'English (US)', value: 'English (US)' },
    { label: 'English (UK)', value: 'English (UK)' },
    { label: 'Esperanto', value: 'Esperanto' },
    { label: 'Estonian', value: 'Estonian' },
    { label: 'Finnish', value: 'Finnish' },
    { label: 'French', value: 'French' },
    { label: 'Frisian', value: 'Frisian' },
    { label: 'Galisian', value: 'Galisian' },
    { label: 'Georgian', value: 'Georgian' },
    { label: 'German', value: 'German' },
    { label: 'Greek', value: 'Greek' },
    { label: 'Gujarati', value: 'Gujarati' },
    { label: 'Haitian Creole', value: 'Haitian Creole' },
    { label: 'Hausa', value: 'Hausa' },
    { label: 'Hawaiian', value: 'Hawaiian' },
    { label: 'Hebrew', value: 'Hebrew' },
    { label: 'Hindi', value: 'Hindi' },
    { label: 'Hmong', value: 'Hmong' },
    { label: 'Hungarian', value: 'Hungarian' },
    { label: 'Icelandic', value: 'Icelandic' },
    { label: 'Igbo', value: 'Igbo' },
]

export const Country = [
    { label: 'U.A.E (United Arab Emirates)', value: 'U.A.E (United Arab Emirates)' },
    { label: 'Albania', value: 'albania' },
    { label: 'Armenia', value: '' },
    { label: 'Argentina', value: '' },
    { label: 'Austria', value: 'austria' },
    { label: 'Australia', value: 'australia' },
    { label: 'Azerbaijan', value: 'azerbaijan' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
    { label: 'Belgium', value: 'belgium' },
    { label: 'Bulgaria', value: 'bulgaria' },
    { label: 'Bahrain', value: 'bahrain' },
    { label: 'Bolivia', value: 'bolivia' },
    { label: 'Brazil', value: 'brazil' },
    { label: 'Slovakia', value: 'Slovakia' },
    { label: 'Sweden', value: 'Sweden' },
    { label: 'Singapore', value: 'Singapore' },
    { label: 'Canada', value: 'canada' },
    { label: 'Slovenia', value: 'Slovenia' },
    { label: 'Serbia', value: 'Serbia' },
    { label: 'Syria', value: 'Syria' },
    { label: 'Taiwan', value: 'Taiwan' },
    { label: 'Tunisia', value: 'Tunisia' },
    { label: 'South Africa', value: 'South Africa' },
    { label: 'Vietnam', value: 'Vietnam' },
    { label: 'Yemen', value: 'Yemen' },
    { label: 'Turkey', value: 'Turkey' },
    { label: 'Ukraine', value: 'Ukraine' },
    { label: 'Thailand', value: 'Thailand' },
    { label: 'United Kingdom', value: 'United Kingdom' },
    { label: 'United States', value: 'United States' },
]

export const PointView = [
    {label: 'First Person Singular (I, me, my, mine)', value: 'first person singular (I, me, my, mine)'},
    {label: 'First Person Plural (we, us, our, ours)', value: 'first person plural (we, us, our, ours)'},
    {label: 'Second Person (you, your, yours)', value: 'second person (you, your, yours)'},
    {label: 'Third Person (he, she, it, they)', value: 'third person (he, she, it, they)'},
]